const assert = require('node:assert/strict');
const fs = require('node:fs');
const {loadApp} = require('./harness');
const TIQ = loadApp(['components.js','skill-icons.js','views.js']);
const raw = fs.readFileSync('tests/highlight-parser.test.js','utf8').match(/const REAL_RESUME = `([\s\S]*?)`;/)[1];
const c = TIQ.intake.buildCandidate({firstName:'Nirmay',lastName:'Sharma'});
c.parsedResume = TIQ.ai.extractResumeData(raw);
TIQ.ai.applyParsedData(c,c.parsedResume,{refresh:true});
c.resumeUpload = {name:'fixture.pdf',parsedAt:new Date().toISOString()};
const entries = TIQ.views._captureVisualEntries(c);
const project = entries.find(e=>e.category==='Project');
assert.match(project.distinction, /Winner.*Congressional App Challenge/, 'explicit award preceding Project belongs to that project block');
assert(project.facts.some(f=>/6 Arkansas counties/.test(f)) && project.facts.some(f=>/75% accuracy/.test(f)));
assert(!entries.find(e=>e.category==='Experience').facts.some(f=>/Congressional|75%/.test(f)));
assert.equal(entries.filter(e=>e.category==='Certifications').reduce((count, entry) => count + entry.facts.length, 0),2);
assert.equal(entries.find(e=>e.category==='Leadership').organization, 'DECA', 'DECA is parsed as the leadership organization, not a December date');
const awarded = TIQ.intake.buildCandidate({firstName:'Alex'});
awarded.resumeUpload = {name:'award.pdf',parsedAt:new Date().toISOString()};
awarded.parsedResume = {rawText:'PROJECTS\nRoute Atlas\n• Built a Python tool for delivery planning.\n• Won Regional Innovation Prize (2024).\nEXPERIENCE\nAssistant\n• Supported 8 students.',projects:[{name:'Route Atlas',description:'Built a Python tool for delivery planning. Won Regional Innovation Prize (2024).'}],experience:[],certifications:[]};
assert.match(TIQ.views._captureVisualEntries(awarded).find(e=>e.category==='Project').distinction, /Won Regional Innovation Prize/, 'awards inside an owned project block are not lost behind its generic purpose');
assert(!TIQ.views._captureVisualEntries(awarded).find(e=>e.category==='Project').facts.some(f=>/8 students/.test(f)), 'an unparsed next Experience section cannot donate its metrics to a project');
const html = TIQ.views._captureHighlightItemHtml(project);
assert(html.includes('resume-highlights__leader') && html.includes('aria-hidden="true"'));
assert(html.includes('<ul class="capture-facts">'));
assert(html.includes('capture-distinction'), 'documented awards use the distinct source-owned callout');
const print = TIQ.views._capturePrintResumeHtml(c);
assert(print.includes('resume-document') && print.includes('Nirmay Sharma') && print.includes('Congressional App Challenge'));
const other = TIQ.intake.buildCandidate({firstName:'Andre',lastName:'Example'});
other.id='andre'; other.notes='Andre-only notes';
TIQ.state.candidates=[c,other]; TIQ.views._captureIndex=1;
const screen = TIQ.views.renderRecruiterCapture();
assert(screen.includes('Andre-only notes') && !screen.includes('CropIntel') && !screen.includes('nirmay'));
assert(!screen.includes('resume-band'), 'no permanent resume block above Resume tab');
c.resumeUpload.sourceUrl='blob:fixture'; TIQ.views._captureIndex=0;
assert(TIQ.views.renderRecruiterCapture().includes('Open original résumé'), 'candidate records retain access to the source resume file');
const malicious=TIQ.intake.buildCandidate({firstName:'<img src=x onerror=bad>'});
malicious.parsedResume={rawText:'<script>bad</script>',education:[],experience:[],projects:[],certifications:[]};
assert(!TIQ.views._capturePrintResumeHtml(malicious).includes('<script>'));
console.log('Capture visual presentation tests passed');
