const assert = require('node:assert/strict');
const {loadApp} = require('./harness');
const T = loadApp(['components.js','skill-icons.js','views.js']);
const source = 'Built a React exception queue with sorting, filters, and loading states, reducing the median time to find a flagged record from 48 to 29 seconds in a ten-user internal usability test.';
const entry = {category:'Experience',name:'Engineer',facts:[source,'Added 34 unit and integration tests for duplicate requests and invalid timestamps; resolved six defects identified during staging review and documented API behavior for the frontend team.'],factEvidence:[{passageId:'a',text:source},{passageId:'b',text:'Added 34 unit and integration tests for duplicate requests and invalid timestamps; resolved six defects identified during staging review and documented API behavior for the frontend team.'}]};
const brief = T.views._captureBriefFacts(entry);
assert(brief.length >= 2 && brief.length <= 3);
assert(brief.every(b => b.text.split(/\s+/).length <= 10));
assert(brief.some(b => /48.*29 seconds/.test(b.text) && /internal/.test(b.text)));
assert(brief.some(b => /34 unit and integration tests/.test(b.text)));
assert(brief.every(b => b.evidence && ['a','b'].includes(b.evidence.passageId)));
const html = T.views._captureHighlightItemHtml(entry);
assert(!html.includes('<details'));
assert.equal((html.match(/<li>/g)||[]).length,brief.length);
assert(html.includes('data-resume-source="a"'));
assert(html.includes('<strong class="capture-metric">34 unit and integration tests</strong>'));
const synthetic = T.views._captureBriefFacts({category:'Project',facts:['Designed an event schema and built an API that identifies late or missing updates using 25,000 synthetic shipment events; distinguished missing data from confirmed delivery exceptions.']});
assert(synthetic.some(b => /25,000 synthetic shipment events/.test(b.text)));
assert(synthetic.every(b=>b.text.split(/\s+/).length <=10));
const support = T.views._captureBriefFacts({facts:['Handle approximately 18 support requests per week involving account access, software installation, and development environments while communicating next steps to nontechnical students.']});
assert(support.some(b => /18 support requests per week/.test(b.text)));
assert(!support.some(b => /View full contribution/.test(b.text)));
assert(T.views._captureMetricHtml('four lab assistants; 24-hour hackathon').includes('<strong class="capture-metric">four lab assistants</strong>'));
assert(T.views._captureMetricHtml('24-hour hackathon').includes('<strong class="capture-metric">24-hour</strong>'));
const change = T.views._captureBriefFacts({facts:['Improved completeness of handoff records from 81% to 96% during a six-week pilot by introducing a checklist.']});
assert(change.some(b => b.text.includes('81') && b.text.includes('96') && /pilot/.test(b.text)));
assert(!change.some(b => /from 81%\.$/.test(b.text)));
const modeledSource = 'Modeled staffing alternatives in Excel and estimated a 12% reduction in average queue time under stated assumptions; presented sensitivity analysis rather than claiming a production result.';
const modeled = {category:'Project',name:'Cross-Dock Process Study',dates:'Jan - May 2026',facts:['Mapped receiving-to-outbound flow for a simulated cross-dock facility and used time observations from a classroom case to identify queue bottlenecks.',modeledSource],factEvidence:[null,{passageId:'model-result',text:modeledSource}]};
const modeledBrief = T.views._captureBriefFacts(modeled);
assert.match(modeledBrief[0].text, /^Estimated 12% reduction in average queue time under stated assumptions\.$/);
assert.equal(modeledBrief[0].evidence.passageId, 'model-result');
assert.equal(modeledBrief.filter(b=>/12%/.test(b.text)).length, 1, 'do not repeat an estimate with its assumptions stripped');
assert(modeledBrief.every(b=>b.text.split(/\s+/).length <=10));
const modeledHtml = T.views._captureHighlightItemHtml(modeled);
assert(modeledHtml.includes('<strong class="capture-metric">12%</strong>'));
assert.match(modeledHtml, /capture-item-heading[\s\S]*resume-highlights__name[\s\S]*capture-item-leader[\s\S]*capture-item-context__dates/);
assert(!/<div class="capture-item-context">[^]*?capture-item-context__dates/.test(modeledHtml));
const priority = T.views._captureBriefFacts({facts:['Built a model using 8,500 synthetic shipment records.',modeledSource,'Wrote documentation for the study.']});
assert(/12%/.test(priority[0].text), 'estimated outcome precedes larger but unrelated data-volume number');
const latency = T.views._captureBriefFacts({facts:['Reduced p95 lookup latency from 420 to 185 milliseconds by tuning indexes and query shapes, verified with application tracing and a representative read workload.']});
assert(latency.some(b => /420→185 milliseconds/.test(b.text)), 'long method clauses cannot hide the primary outcome');
const diagnosis = T.views._captureBriefFacts({facts:['Introduced service-level dashboards, alert ownership, and incident runbooks; reduced median incident diagnosis time from 52 to 31 minutes across 14 comparable incidents.']});
assert(diagnosis.some(b => /52→31 minutes.*14 comparable incidents/.test(b.text)), 'keep comparison scope within the word budget');
const inventory = T.views._captureBriefFacts({facts:['Worked 20 hours weekly while attending college, scanning receipts and reconciling bin discrepancies across a 3,000-SKU operation.','Helped train four new associates on scanning and discrepancy reporting.']});
assert(inventory.some(b=>/3,000-SKU/.test(b.text)), 'retain material operational scope, not only weekly hours');
assert(T.views._captureMetricHtml('approximately 1.8 million daily messages').includes('<strong class="capture-metric">1.8 million daily messages</strong>'));
console.log('PASS concise card bullets, quantities, qualifiers, and original source ownership');
