const assert = require('node:assert/strict');
const fs = require('node:fs');
const {loadApp} = require('./harness');
const TIQ = loadApp(['components.js','skill-icons.js','views.js']);
const c = TIQ.intake.buildCandidate({firstName:'Fixture',lastName:'Candidate',notes:'Own candidate draft'});
c.notes = 'Own candidate draft';
c.resumeUpload = {name:'fixture.pdf',parsedAt:new Date().toISOString(),sourceUrl:'blob:fixture'};
c.parsedResume = TIQ.ai.extractResumeData('Fixture Candidate\nEDUCATION\nNorthwind University\nPROJECTS\nInventory Monitor | Python\n• Built an inventory monitor tracking 30 stores.\nCERTIFICATIONS\nMicrosoft Office Specialist');
c.parsedResume.certifications = ['Microsoft Office Specialist'];
TIQ.state.candidates = [c]; TIQ.views._captureIndex = 0;
const html = TIQ.views.renderRecruiterCapture();
assert(!html.includes('capture-evidence-header'), 'tabs replace the redundant Evidence header, not a hidden spacer');
assert(!html.includes('capture-evidence-hint') && !html.includes('Select Resume or Notes to view candidate records and voice notes.'), 'redundant instruction is removed above the tabs');
assert(html.includes('CERTIFICATIONS') && html.includes('Microsoft Office Specialist'), 'resume document retains its certification section and values');
assert(html.includes('Open original résumé') && html.includes('href="blob:fixture"'), 'workspace links to an available original resume');
assert(!html.includes('Original résumé text') && !html.includes('drawer-raw'), 'workspace omits the raw resume text disclosure');
assert(html.includes('data-capture-details-back'), 'mobile back navigation remains');
assert(html.includes('<label for="captureNotes" class="capture-section-title">Recruiter Notes</label>'));
assert(html.includes('Own candidate draft'));
for(const tab of ['resume','notes']) assert(html.includes('id="capture-panel-'+tab+'"'));
assert(!html.includes('id="capture-panel-voice"'), 'voice controls live in Notes rather than a third tab');
const css = fs.readFileSync('styles.css','utf8');
assert(css.includes('--capture-workspace-padding: 20px'));
assert(css.includes('#view-capture .resume-document { padding: 28px 32px; line-height: 1.6; }'));
assert(css.includes('#view-capture .resume-document__section { margin-top: 22px; }'));
assert(css.includes('#view-capture .drawer-panel.is-active { overflow-y: auto; min-height: 0; flex: 1 1 0; }'), 'resume content can scroll fully inside the evidence panel');
assert(/#view-capture \.resume-highlights \{[^}]*flex:\s*1 1 0;[^}]*overflow-y:\s*auto;/.test(css), 'highlight panel uses available card height and scrolls');
assert(css.includes('#view-capture .resume-highlights__list { flex: 0 0 auto; justify-content: flex-start;'), 'highlight groups stack naturally without large distributed gaps');
assert(css.includes('#view-capture .resume-highlights__entry .capture-facts li { font-size: 16px;'), 'candidate evidence text is large enough to read');
assert(css.includes('#view-capture #captureNotes'));
assert(/#view-capture \.capture-card__swipe-hint \{ font-size:\s*14px;/.test(css), 'review and follow-up actions are legible at card scale');
assert(/#view-capture \.resume-highlights \{[^}]*flex:\s*1 1 0;[^}]*overflow-y:\s*auto;/.test(css), 'highlights consume available card height and scroll without hiding lower entries');
console.log('PASS Capture workspace spacing, header removal, and unchanged tab/notes structure');
