const assert = require('node:assert/strict');
const fs = require('node:fs');
const { loadApp } = require('./harness');
const TIQ = loadApp(['components.js', 'skill-icons.js', 'views.js']);
const raw = fs.readFileSync('tests/highlight-parser.test.js', 'utf8').match(/const REAL_RESUME = `([\s\S]*?)`;/)[1];
const c = TIQ.intake.buildCandidate({firstName:'Nirmay',lastName:'Sharma'});
c.parsedResume = TIQ.ai.extractResumeData(raw);
TIQ.ai.applyParsedData(c, c.parsedResume, {refresh:true});
c.resumeUpload = {name:'fixture.pdf',parsedAt:new Date().toISOString()};
c.skills = ['Python','Java','JavaScript','HTML','CSS','Excel','Data Visualization','Operations','Logistics','Leadership','PowerPoint','Word','Computational Thinking'];
const card = TIQ.views._buildCardHtml(c, true);
assert(!card.includes('card-more'), 'summary card removes the obsolete More disclosure');
assert(!card.includes('audioRecordBtn'), 'recording belongs in evidence, not the decision card');
assert(TIQ.views.renderRecruiterCapture().includes('popover="auto"'), 'remaining skills use a native dismissible popover');
assert(card.includes('data-skill-index'), 'skill fitting uses actual candidate skills');
const entries = TIQ.views._resumeHighlightEntries(c);
assert.equal(entries.filter(e => e.category === 'Certifications').length, 2, 'the full distinct credential set is retained');
const categoryHeadings = Array.from(TIQ.views._resumeHighlightsHtml(c).matchAll(/resume-highlights__category">([^<]*)/g), match => match[1]);
assert.equal(new Set(categoryHeadings).size, categoryHeadings.length, 'each category heading renders once even when a category has multiple entries');
assert(entries.some(e => e.description.includes('14 students') && /2-3 hours weekly/.test(e.description)), 'scope and hours remain supported by the resume');
assert(entries.some(e => /6 Arkansas counties/.test(e.description)), 'project scope remains visible');
assert(entries.every(e => !e.description.includes('...') && !e.description.includes('…')));
assert(entries.every(e => e.name || e.description || e.distinction), 'omit empty categories without dropping standalone source-backed awards');
assert(entries.some(e => e.category === 'Leadership' && /DECA/.test(e.organization)), 'organization comes only from the matching role source block');
assert(entries.some(e => e.category === 'Leadership' && /1st Place State Winner/.test(e.distinction)), 'a role-linked placement stays with its leadership context');
assert(!entries.some(e => e.category === 'Award' && /1st Place State Winner/.test(e.distinction || e.description)), 'do not repeat a leadership achievement as a separate group');
assert(card.includes('capture-metric'), 'impact metrics receive restrained emphasis');
assert(!card.includes('75% revenue'), 'no invented impact');
assert(TIQ.views.renderRecruiterCapture().includes('audioRecordBtn'), 'existing recorder remains in the evidence workspace');
assert(!fs.readFileSync('views.js','utf8').includes('_captureMoreIndex'), 'obsolete disclosure state is removed');
assert.equal(TIQ.views._captureTldr('International Competitor: Qualified for and competed at ICDC.', ''), 'Qualified for and competed at ICDC.', 'award summary retains a complete qualification rather than a dangling conjunction');
const projectCandidate = TIQ.intake.buildCandidate({firstName:'Project',lastName:'Example'});
projectCandidate.resumeUpload = {name:'projects.pdf',parsedAt:new Date().toISOString()};
projectCandidate.parsedResume = {rawText:'PROJECTS\nRoute Atlas\nBuilt a Python map for delivery planning across 12 routes.\nStock Monitor\nDeveloped a SQL dashboard for inventory tracking across 90 stores.',projects:[{name:'Route Atlas',description:'Built a Python map for delivery planning across 12 routes.'},{name:'Stock Monitor',description:'Developed a SQL dashboard for inventory tracking across 90 stores.'}],experience:[],certifications:[],skills:[]};
const projectEntries = TIQ.views._resumeHighlightEntries(projectCandidate);
assert(!projectEntries.find(e => e.name === 'Route Atlas').description.includes('90 stores'), 'project summaries cannot borrow the next project result');
const longContribution = 'Built an inventory dashboard using Python and SQL for a cross-functional operations group that needed dependable reporting across several locations. Reduced costs by 25% and saved $12,000 while supporting 200 users.';
const compact = TIQ.views._captureTldr(longContribution, 'Inventory dashboard');
assert(compact.includes('25%') && compact.includes('$12,000') && compact.includes('200 users') && compact.includes('Python'), 'long prose preserves results, scale and tools');
assert(compact.includes('Reduced costs by 25%') && compact.includes('saved $12,000'), 'quantities retain their result context rather than becoming ambiguous bare metrics');
assert(!compact.includes('…') && !compact.includes('...'));
assert(TIQ.views._captureMetricHtml('1st Place State Winner').includes('capture-metric'), 'source-supported placements receive the same restrained metric emphasis');
console.log('Capture summary tests passed');
