const assert = require('node:assert/strict');
const fs = require('node:fs');
const {loadApp} = require('./harness');
const TIQ = loadApp(['components.js','skill-icons.js','views.js']);
const raw = fs.readFileSync('tests/highlight-parser.test.js','utf8').match(/const REAL_RESUME = `([\s\S]*?)`;/)[1];
const c = TIQ.intake.buildCandidate({firstName:'Nirmay',lastName:'Sharma'});
c.parsedResume = TIQ.ai.extractResumeData(raw);
TIQ.ai.applyParsedData(c,c.parsedResume,{refresh:true});
c.resumeUpload = {name:'fixture.pdf',parsedAt:new Date().toISOString()};
assert(!TIQ.views._topSkillsHtml({...c,skills:['Python']}).includes('prov-dot'), 'Top skills has no decorative provenance dot');
const entries = TIQ.views._resumeHighlightEntries(c);
const experience = entries.find(e => e.category === 'Experience');
assert(experience.description.includes('14 students') && experience.description.includes('2-3 hours weekly'));
assert(!/Place|Winner|ICDC/.test(experience.description), 'Experience cannot absorb awards');
const leadership = entries.find(e => e.category === 'Leadership');
assert(leadership && /DECA/.test(leadership.organization) && /1st Place State Winner/.test(leadership.distinction), 'competition achievement and organization stay with the explicit leadership role');
assert(leadership.description.includes('Qualified for and competed at ICDC'), 'leadership accomplishment remains attached to the leadership section');
const untruncated = TIQ.views._compactCaptureEntry({category:'Experience',name:'Assistant',description:'assisting 14 students · daily operations and logistics · 2-3 hours weekly',facts:['assisting 14 students','daily operations and logistics','2-3 hours weekly'],dates:'Aug 2025 – Present'});
assert.equal(untruncated.description,'assisting 14 students · daily operations and logistics · 2-3 hours weekly', 'compact presentation never drops source details');
assert.equal(untruncated.facts.length,3, 'all facts remain available in compact mode');
const contaminated = structuredClone(c);
contaminated.parsedResume.experience.find(e => /Teaching/.test(e.title)).description += '\nAWARDS\n1st Place State Winner · 2nd Place · 5th Place';
assert(!/Place|Winner/.test(TIQ.views._resumeHighlightEntries(contaminated).find(e => e.category === 'Experience').description));
const mixed = TIQ.intake.buildCandidate({firstName:'Jordan'});
mixed.resumeUpload = {name:'mixed.pdf',parsedAt:new Date().toISOString()};
mixed.parsedResume = {rawText:'Teaching Assistant\nSupported 14 students and executed operations 2-3 hours weekly.\nAwards\n1st Place State Winner',experience:[{title:'Teaching Assistant',description:'Supported 14 students and executed operations 2-3 hours weekly.\nAwards\n1st Place State Winner'}],projects:[],skills:[],certifications:[]};
assert(!TIQ.views._resumeHighlightEntries(mixed).some(e => e.category === 'Experience'), 'content outside a recognized section is omitted rather than promoted to a role');
const css = fs.readFileSync('styles.css','utf8');
assert(css.includes('--capture-available-height'), 'frame derives from measured available viewport');
const viewsSource = fs.readFileSync('views.js','utf8');
assert(!/\.observe\(document\.querySelector\(['"]\.topbar['"]\)\)/.test(viewsSource), 'Capture setup does not observe the removed shared topbar');
assert(/TIQ\.views\.initCaptureEvents\s*=\s*function\s*\(\)[\s\S]*?TIQ\.views\.initSwipeEngine\(\)/.test(viewsSource), 'Capture event setup reaches the swipe engine');
assert(!/#view-capture \.capture-metric \{ color: var\(--brand\)/.test(css), 'noninteractive metrics are not blue');
const empty = TIQ.views._resumeHighlightsHtml(TIQ.intake.buildCandidate({firstName:'Andre'}));
assert(empty.includes('No highlights yet'), 'sparse state is understated rather than a stretched placeholder');
console.log('Capture stability tests passed');
