const fs = require('fs');
const path = require('path');
const assert = require('node:assert/strict');
const { loadApp } = require('./harness');

const TIQ = loadApp(['views.js']);
const html = TIQ.views.renderKiosk();
assert.match(html, /kiosk-poster__columns[\s\S]*kiosk-instructions[\s\S]*kiosk-qr-panel/, 'instructions and QR share a centered two-column container');
assert.doesNotMatch(html, /kiosk-poster__qr-info/, 'check-in info is not left floating at the poster edge');
assert.match(html, /kiosk-brand-logo[^>]*>[\s\S]*kiosk-poster__leader" aria-hidden="true"[\s\S]*kiosk-poster__motto/, 'footer connects branding with a decorative leader');
assert.match(html, /kiosk-poster__band"[\s\S]*id="kioskEditQr"[\s\S]*kiosk-poster__columns"[\s\S]*kiosk-instructions__heading[\s\S]*kioskInstructionsTitle/, 'QR settings control hangs at the card edge above the centred check-in group');
const css = fs.readFileSync(path.join(__dirname, '..', 'styles.css'), 'utf8');
assert.match(css, /\.kiosk-poster__columns\s*\{[^}]*margin-inline:\s*auto[^}]*gap:\s*64px/s);
assert.match(css, /--kiosk-heading-ink-offset/);
assert.match(css, /--kiosk-qr-ink-offset/);
assert.match(css, /\.kiosk-poster__header\s*\{[^}]*border-bottom:\s*1px solid #[\da-f]{6}/i, 'event header divider uses a visible opaque gray');
assert.match(css, /\.kiosk-poster__leader\s*\{[^}]*border-bottom:\s*1px dotted #[\da-f]{6}[^}]*opacity:\s*1(?:\.0)?\b/i, 'footer connector uses a full-opacity gray dotted line');
assert.match(css, /\.kiosk-poster \.kiosk-qr-panel\s*\{[^}]*--kiosk-qr-frame:\s*min\(100%,\s*420px,\s*max\(180px,\s*calc\(100dvh - 420px\)\)\)/s, 'QR block uses the reclaimed header space in its dvh height budget');
assert.match(css, /\.kiosk-poster \.kiosk-qr-actions\s*\{[^}]*width:\s*var\(--kiosk-qr-ink-width[^}]*gap:\s*12px/s, 'action row spans the visible black QR pattern with a fixed gap');
assert.match(css, /\.kiosk-poster \.kiosk-qr-actions\s*\{[^}]*calc\(var\(--kiosk-qr-frame\) - 24px\)/s, 'action row falls back to the canvas width before the pattern is measured');
assert.match(css, /\.kiosk-poster \.kiosk-qr-panel\s*\{[^}]*margin-bottom:\s*calc\(-1 \* var\(--kiosk-qr-ink-offset/s, 'QR column reclaims its ink offset so the centred box ends at the painted buttons');
assert.match(css, /\.kiosk-poster \.kiosk-instructions\s*\{[^}]*margin:\s*0 0 calc\(-1 \* var\(--kiosk-heading-ink-offset/s, 'instructions column reclaims its ink offset so the centred box ends at the painted steps');
assert.match(css, /@media \(max-width: 1100px\)\s*\{[\s\S]*?\.kiosk-poster \.kiosk-qr-panel\s*\{[^}]*top:\s*0;[^}]*margin-bottom:\s*0;/, 'stacked layout drops the ink offset and the margin that matched it');
assert.match(css, /\.kiosk-poster \.kiosk-qr-container\s*\{[^}]*padding:\s*12px/);
assert.match(css, /\.kiosk-poster \.kiosk-qr-panel\s*\{[^}]*gap:\s*22px/);
assert.match(css, /\.kiosk-poster \.kiosk-instructions__steps\s*\{[^}]*gap:\s*clamp\(16px/s);
assert.match(css, /\.kiosk-poster \.kiosk-brand-logo\s*\{[^}]*width:\s*clamp\(220px/);
assert.match(css, /@media print\s*\{[\s\S]*\.kiosk-poster\s*\{[^}]*position:\s*fixed[\s\S]*\.kiosk-qr-actions\s*\{\s*display:\s*none/);
assert.match(css, /@media print\s*\{[\s\S]*@page\s*\{\s*size:\s*landscape/);
assert.match(css, /@media print\s*\{[\s\S]*\.kiosk-poster__columns\s*\{[^}]*grid-template-columns:\s*minmax\(0,\s*1fr\)\s+minmax\(0,\s*420px\)/s, 'print keeps the poster two-column instead of using the narrow-screen stack');
assert.match(css, /@media print\s*\{[\s\S]*\.kiosk-poster__footer\s*\{[^}]*flex-direction:\s*row/s, 'print keeps the inline footer branding');
assert.match(css, /@media print\s*\{[\s\S]*\.kiosk-poster\s*,\s*\.kiosk-poster\s*\*\s*\{[^}]*print-color-adjust:\s*exact/s, 'poster print output requests exact brand/background colors');
console.log('Check-in layout regression checks passed');
