const assert = require('node:assert/strict');
const fs = require('node:fs');
const {loadApp} = require('./harness');
const T = loadApp(fs.existsSync('research-study.js') ? ['research-study.js'] : []);
assert.equal(typeof T.study,'object','explicit controlled-study observations are available');
const R = T.study;
const study = R.create({name:'Synthetic comparison',dataset:'fixture-v1',taskDefinition:'Capture supplied identity and review source-supported statements',requiredFields:['firstName','lastName','email'],consistencyRubric:'Identity, source, status, and next step use the same structure',supportRubric:'Supported only when the supplied passage supports the whole statement',question:'How confident are you that your next step is supported? 1 low, 5 high',confirmed:true});
assert.equal(R.compare(study).capture.Manual.mean,null,'no data is not zero benefit');
assert.throws(()=>R.start(study,{participant:'P1',method:'Manual',task:'capture',pair:'pair-1'}), /synthetic/i);
const t = R.start(study,{participant:'P1',method:'Manual',task:'capture',pair:'pair-1',synthetic:true},1000);
assert.throws(()=>R.start(study,{participant:'P2',method:'TalentIQ',task:'capture',pair:'pair-1',synthetic:true}),/active/i);
R.finish(study,t.id,{completed:true,fields:{firstName:'Sample',lastName:'Person',email:'s@example.test'},consistent:3,consistencyTotal:4,confidence:4,errors:1,feedback:'Useful',originalDraft:'Original',finalDraft:'Corrected',edits:[{type:'factual correction',count:1}],statements:[{statement:'Built a report',source:'Built a report for 12 branches',judgment:'Supported'}]},11000);
const tiq = R.start(study,{participant:'P1',method:'TalentIQ',task:'capture',pair:'pair-1',synthetic:true,candidateIds:['explicitly-assigned']},12000);
assert.equal(typeof R.stop,'function','task-boundary stop precedes observation entry');
R.stop(study,tiq.id,17000);
R.finish(study,tiq.id,{completed:true,fields:{firstName:'Sample',lastName:'Person',email:'s@example.test'},consistent:4,consistencyTotal:4,confidence:5,errors:0},22000);
const incomplete = R.start(study,{participant:'P2',method:'Manual',task:'capture',pair:'pair-2',synthetic:true},20000);
R.abandon(study,incomplete.id,'Could not finish',23000);
assert.throws(()=>R.finish(study,incomplete.id,{completed:true},24000),/active/i);
const comparison = R.compare(study);
assert.equal(comparison.capture.Manual.n,1);
assert.equal(comparison.capture.Manual.mean,10);
assert.equal(comparison.capture.TalentIQ.mean,5);
assert.equal(comparison.capture.paired.n,1);
assert.equal(comparison.capture.paired.mean,-5);
assert.equal(comparison.coverage.Manual.mean,100);
assert.equal(comparison.consistency.Manual.mean,75);
assert.equal(comparison.review.Manual.mean,null);
assert.equal(R.support(study).supported,1);
assert.equal(R.support(study).assessed,1);
R.addAccessibility(study,{check:'Keyboard',date:'2026-10-07',method:'Manual task walkthrough',result:'Needs remediation',remediation:'Fix focus order',limitation:'One browser tested'});
const exported = R.export(study);
assert.equal(exported.trials.length,3);
assert.equal(exported.trials[2].includedInCompletedTime,false);
assert.equal(exported.definitions.requiredFields.length,3);
assert.equal(exported.accessibility[0].check,'Keyboard');
assert.ok(T.__testStorageStore['talentiq-study-v1'].includes('Could not finish'),'study persists separately from candidate metrics');
assert.equal(T.state.metrics.length,0,'ordinary metrics cannot create observations');
assert.throws(()=>R.finish(study,t.id,{completed:true,confidence:9}),/active/i);
console.log('PASS controlled study: true timings, explicit synthetic assignment, paired methods, exclusions, quality, feedback, export');
