const fs = require('node:fs');
const assert = require('node:assert/strict');
const {loadApp} = require('./harness');
const T = loadApp(['analytics.js','components.js','skill-icons.js','views.js','research-study.js'].concat(fs.existsSync('research-workspace.js') ? ['research-workspace.js'] : []));
const empty = T.views.renderMetrics();
assert.ok(empty.includes('Create study'),'a study must be defined before measuring outcomes');
assert.ok(empty.includes('Not measured'));
const s = T.study.create({name:'Study fixture',dataset:'v1',taskDefinition:'Equivalent supplied task',requiredFields:['firstName','email'],consistencyRubric:'Checks',supportRubric:'Whole claim supported',question:'Confidence 1 low to 5 high',confirmed:true});
T.views.researchState.studyId = s.id;
T.views.researchState.tab = 'trial';
assert.ok(T.views.renderMetrics().includes('Start trial'));
const t = T.study.start(s,{participant:'P1',pair:'one',method:'Manual',task:'review',synthetic:true},1000);
const active = T.views.renderMetrics();
assert.ok(active.includes('Finish trial'));
assert.ok(active.includes('Abandon trial'));
assert.ok(active.includes(t.id));
T.views.researchState.tab = 'compare';
const compare = T.views.renderMetrics();
assert.ok(compare.includes('Paired difference'));
assert.ok(compare.includes('Not measured'));
assert.ok(compare.includes('Completed observations'));
T.views.researchState.tab = 'evidence';
const evidence = T.views.renderMetrics();
assert.ok(evidence.includes('Source passage'));
assert.ok(evidence.includes('Keyboard'));
assert.ok(evidence.includes('Zoom / reflow'));
assert.ok(!evidence.includes('Recruiter activity leaderboard'));
console.log('PASS research screens: frozen definitions, active trials, honest empty comparisons, human support and accessibility evidence');
