const assert = require('node:assert/strict');
const {loadApp}=require('./harness');
const T=loadApp(require('node:fs').existsSync('review-contact.js') ? ['review-contact.js'] : []);
assert(T.reviewContact,'Contact helper exists');
const C=T.reviewContact;
assert.equal(C.suggest(new Date('2026-10-09T17:00:00Z'),'America/Chicago').date,'2026-10-12');
assert.equal(C.suggest(new Date('2026-10-10T17:00:00Z'),'America/Chicago').date,'2026-10-12');
assert.equal(C.suggest(new Date('2026-12-31T10:00:00Z'),'UTC').date,'2027-01-01');
assert.equal(C.suggest(new Date('2026-10-08T00:30:00Z'),'America/Chicago').date,'2026-10-08');
const c=T.normalizeCandidate(T.intake.buildCandidate({firstName:'Synthetic',email:'test@example.invalid'},{state:T.state}));
T.state.candidates=[c];T.state.activeRecruiterId=T.CONFIG.recruiters[0].id;c.summary='Known observation';T.reviewWorkflow.approve(c,[]);
const draft=C.prepare(c,new Date('2026-10-09T17:00:00Z'),'America/Chicago');
assert.equal(draft.time,'12:00');assert.equal(draft.duration,30);
assert(!draft.body.includes('speaking with us'),'template must not invent a conversation');
draft.body='Recruiter edited message';assert.equal(C.prepare(c).body,draft.body,'no regeneration');
const url=C.calendar(c,draft,new Date('2026-10-09T17:00:00Z'));
assert(url.includes('20261012T170000Z') && url.includes('20261012T173000Z'));
assert(url.includes('add=test%40example.invalid'));assert(!url.includes('meet.google'));
C.record(c,'prepared','calendar');assert.equal(c.approvalStatus,'Approved');
assert.equal(c.contactHistory[0].kind,'prepared');
C.record(c,'sent','calendar');assert.equal(c.contactHistory[1].selfReported,true);
assert.equal(c.recordStatus,'New');
assert.equal(JSON.parse(T.__testStorageStore.talentiq_state_v1).candidates[0].outreachDraft.body,'Recruiter edited message');
assert.throws(()=>C.calendar(c,{...draft,time:'bad'}),/time/i);
assert.throws(()=>C.email(c,{...draft,time:'bad'}),/time/i);
assert.throws(()=>C.calendar(c,{...draft,timezone:'Unknown/Zone'}),/timezone/i);
assert.throws(()=>C.calendar(c,draft,new Date('2026-12-01T00:00:00Z')),/future/i);
assert.throws(()=>C.calendar(c,{...draft,to:''}),/email/i);
assert.throws(()=>C.calendar(c,{...draft,date:'2026-02-30'}),/date/i);
assert.throws(()=>C.calendar(c,{...draft,date:'2026-11-01',time:'01:30'},new Date('2026-10-01T00:00:00Z')),/ambiguous/i);
assert.throws(()=>C.calendar(c,{...draft,date:'2027-03-14',time:'02:30'},new Date('2026-10-01T00:00:00Z')),/exist/i);
assert.equal(C.safeLink('javascript:alert(1)'),'');assert.equal(C.safeLink('https://github.com/example'),'https://github.com/example');
assert.equal(C.safeLink('https://user:password@example.com'),'');
console.log('PASS suggested schedule, DST safety, contact persistence and independent certification');
