const assert = require('node:assert/strict');
const fs = require('node:fs');
const {loadApp} = require('./harness');
const files = ['analytics.js','components.js','skill-icons.js','views.js'];
if (fs.existsSync('review-workspace.js')) files.push('review-workspace.js');
const T = loadApp(files), W = T.reviewWorkflow;
T.state.candidates = [T.intake.buildCandidate({firstName:'Synthetic',lastName:'Reviewer',email:'sample@example.test'},{state:{candidates:[]}})];
const c = T.state.candidates[0]; c.id = 'review-sample'; c.recordStatus = 'Follow-Up'; c.eventId = 'fair'; c.summary = 'A recorded draft';
c.parsedResume = T.ai.extractResumeData('Synthetic Reviewer\nEXPERIENCE\nAnalyst | Example Org | 2024\n• Built a report using SQL for 12 branches.\nPROJECTS\nProject: Route Dashboard\n• Built a dashboard for 3 routes.\nSKILLS\nSQL, Python');
c.skills = ['SQL','Python'];
T.views.reviewState.filters.event = 'fair';
let html = T.views.renderReview();
assert.ok(html.includes('review-simplified'), 'Review uses recap / shared reference panels');
assert.ok(html.includes(T.views._buildCardHtml(c,false).replace(/capture-skills-popover/g,'review-card-skills')), 'shared Capture card with Review IDs, without swipe hints');
assert.ok(html.includes('Approve recap') && html.includes('Reject draft') && html.includes('Next-step notes'));
assert.ok(html.includes('Extracted resume text') && html.includes('Candidate reference'));
assert.ok(html.includes('Previous') && html.includes('Next'));
assert.ok(!html.includes('capture-card__swipe-hint'));
assert.ok(html.includes('Closed'));
T.views.reviewState.filters = {event:'fair',status:'Follow-Up',verification:'all',search:''};
T.views.reviewState.selected = c.id;
W.setDraft(c,{summary:'Unsaved correction'});
W.changeStatus(c,'Closed');
html = T.views.renderReview();
assert.ok(html.includes('no longer matches'), 'moved candidate detail retained until navigation');
assert.ok(html.includes('Unsaved correction'));
const compare = T.views.reviewComparisonHtml([c,c]);
assert.ok(compare.includes('Supporting evidence') && compare.includes('Closed'));
T.views.enableRetainedResults(); // Explicit retained-only test; active app never calls this.
const result = T.views.renderAnalytics();
assert.ok(result.includes('Work remaining') && result.includes('Required-field coverage'));
assert.ok(result.includes('Intake-required definition') && result.includes('Optional gaps'));
assert.ok(!result.includes('Field completeness'), 'optional fields not counted as essential completeness');
const before = {...T.views.reviewState.filters};
T.views.openResultsReview({status:'Closed'},false);
assert.equal(T.views.reviewState.filters.status, 'Closed');
assert.equal(T.views.reviewState.filters.verification, 'all');
T.views.restoreReviewContext(false);
assert.deepEqual(JSON.parse(JSON.stringify(T.views.reviewState.filters)),before);
console.log('PASS review and event-results rendering, shared cards, retained drafts and drill-down context');
