const assert=require('node:assert/strict');
const fs=require('node:fs');
const path=require('node:path');
const {loadApp}=require('./harness');
const T=loadApp(['analytics.js','components.js','skill-icons.js','views.js','review-contact.js','review-workspace.js']);
const V=T.views;
T.state.candidates=['New','Reviewed','Follow-Up','Interview Requested','Closed'].map((status,i)=>Object.assign(T.normalizeCandidate(T.intake.buildCandidate({firstName:'Synthetic '+i,email:i+'@example.invalid'},{state:T.state})),{id:'c'+i,eventId:T.currentEventId(),recordStatus:status,skills:['SQL','Python','Java','C++','Git'],summary:'Factual recap'}));
T.state.candidates[1].contactHistory=[{kind:'sent',selfReported:true,timestamp:'2026-10-07T12:00:00Z'}];
T.state.candidates[1].outreachDraft={body:'Existing edited invitation',time:'14:30',timezone:'America/Chicago'};
const history=JSON.stringify(T.state.candidates[1].contactHistory);
const html=V.renderReview();
assert(html.indexOf('candidate-card review-candidate-card')<html.indexOf('Recruiter recap'),'card precedes recap on left');
assert(html.includes('review-tab-contact') && !html.includes('review-tab-profile'));
assert(html.includes('Inspect card and evidence') && html.includes('Choose a next step'));
assert(html.includes('data-review-action="compare-open"') && !html.includes('role="tab" id="review-tab-comparison"'));
assert(html.includes('id="contact-date"') && html.includes('id="contact-body"'),'outreach is already expanded');
assert.match(html, /class="review-interview-row"[\s\S]*id="contact-date"[\s\S]*id="contact-time"[\s\S]*id="contact-timezone"[\s\S]*id="contact-duration"/, 'interview date, time, timezone, and duration share one wireframe row');
assert.equal((html.match(/class="review-interview-field"/g) || []).length, 4, 'each schedule label is grouped with its input for leader alignment');
const styles=fs.readFileSync(path.join(__dirname,'..','styles.css'),'utf8');
assert.match(styles,/\.review-simplified \.review-interview-row \{[^}]*margin-block:\s*12px/, 'schedule controls have breathing room from adjacent outreach fields');
assert(!html.includes('contact-sent-confirm') && !html.includes('data-review-action="contact-sent"') && !html.includes('Hide outreach') && !html.includes('Contact history'),'remove the controls in image 1');
assert(html.includes('<details open id="reviewNextSteps"><summary>Choose a next step</summary>'),'next steps open by default');
assert.equal(JSON.stringify(T.state.candidates[1].contactHistory),history,'hidden historical data remains intact');
assert(html.includes('Existing edited invitation') && html.includes('value="14:30"'),'opening outreach preserves edited message and schedule');
assert(html.includes('LinkedIn: Not captured') && html.includes('GitHub: Not captured') && html.includes('Portfolio: Not captured'));
assert(!html.includes('capture-card__swipe-hint'));
const comparison=V.reviewComparisonHtml(T.state.candidates.slice(0,2));
T.state.candidates[0].technicalInterests=['Databases'];T.state.candidates[0].notes='Recruiter observation';
assert(V.reviewComparisonHtml(T.state.candidates.slice(0,2)).includes('Databases'),'structured interests shown in comparison');
const ids=Array.from((html+comparison).matchAll(/\bid="([^"]+)"/g),m=>m[1]);
assert.equal(new Set(ids).size,ids.length,'Review and comparison contain no duplicate IDs');
assert(comparison.includes('review-compare-skills-0') && comparison.includes('review-compare-skills-1'));
assert(comparison.includes('data-comparison-evidence="notes"'));
console.log('PASS card-left reuse, namespaced IDs, expanded Contact/next steps and separate comparison');
