const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const {loadApp} = require('./harness');
const T = loadApp(['components.js','skill-icons.js','views.js']);
const c = T.normalizeCandidate({id:'independent',firstName:'Sample',lastName:'Person',summary:'Supplied statement',priority:'Low',recordStatus:'New',approvalStatus:'Pending',auditLog:[]});
T.state.candidates=[c]; T.state.activeRecruiterId='r1';
T.reviewWorkflow.approve(c);
const approved=c.approvedVersion;
T.views._rerenderCapture=()=>{}; T.showUndoToast=()=>{}; T.showToast=()=>{};
T.views._captureIndex=0; T.views._setCaptureStatus('Reviewed');
T.addAuditEntry(c,'DRAFT_CHECK_NOTE','Later verification observation must survive sorting undo');
T.views._undoLastCaptureAction();
assert.equal(c.recordStatus,'New');
assert.equal(c.approvedVersion,approved);
assert.ok(c.auditLog.some(e=>e.action==='DRAFT_CHECK_NOTE'),'sorting undo never discards subsequent evidence');
const store = Object.assign({},T.__testStorageStore);
const window = {TIQ:{},addEventListener:()=>{}};
const ctx = vm.createContext({window,localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},navigator:{},console,get TIQ(){return window.TIQ;}});
for(const f of ['config.js','data.js','workflow.js']) vm.runInContext(fs.readFileSync(f,'utf8'),ctx,{filename:f});
const reloaded=window.TIQ.state.candidates.find(x=>x.id===c.id);
window.TIQ.saveState();
assert.equal(reloaded.approvalStatus,'Approved','content-version approval survives a genuine reload');
assert.equal(window.TIQ.reviewWorkflow.label(reloaded),'Approved');
console.log('PASS independent Capture undo, preserved audit evidence, persisted approval after reload');
