const assert = require('node:assert/strict');
const { loadApp } = require('./harness');
const T = loadApp();
assert.equal(typeof T.reviewWorkflow, 'object', 'shared review workflow is available');
const W = T.reviewWorkflow;
T.state.activeRecruiterId = 'R1';
function candidate(id, extra) {
  const c = Object.assign({id, firstName:'Sample', lastName:'Person', email:'sample@example.test', summary:'Recorded draft', recordStatus:'Follow-Up', priority:'High', approvalStatus:'Pending', auditLog:[]}, extra);
  T.state.candidates.push(c); return c;
}
T.state.candidates = [];
const c = candidate('a');
W.changeStatus(c, 'Reviewed');
assert.equal(c.approvalStatus, 'Pending');
assert.ok(!c.approverId && !c.approvalTimestamp);
assert.equal(c.auditLog.at(-1).action, 'STATUS_CHANGED');
W.changeStatus(c, 'Follow-Up');
W.setDraft(c, {summary:'Edited exact draft', nextStepNotes:'Ask about availability'});
assert.equal(c.summary, 'Recorded draft', 'typing does not save or approve');
W.approve(c);
assert.equal(c.summary, 'Edited exact draft');
assert.equal(c.approvalStatus, 'Approved');
assert.equal(c.recordStatus, 'Follow-Up');
assert.equal(c.priority, 'High');
assert.equal(c.approvedVersion.summary, c.summary);
assert.equal(c.approvedVersion.fingerprint, W.fingerprint(c));
assert.equal(c.approverId, 'R1');
assert.equal(W.hasUnsavedDrafts(), false);
W.normalize(c);
assert.equal(c.approvalStatus, 'Approved', 'versioned approval survives normalization');
assert.throws(() => W.reject(c, ''), /reason/i);
W.reject(c, 'Statement needs checking');
assert.equal(c.recordStatus, 'Follow-Up');
assert.equal(c.approvalStatus, 'Rejected');
W.setDraft(c, {summary:'Corrected statement'}); W.saveDraft(c);
assert.equal(c.approvalStatus, 'Pending');
assert.equal(c.summarySource, 'recruiter');
assert.deepEqual(Array.from(c.traceability), [], 'edited text does not inherit old citations');
assert.ok(c.verificationHistory.some(x => x.kind === 'approved'), 'prior approved version retained');
W.approve(c); c.notes = 'New information'; T.saveState();
assert.equal(c.approvalStatus, 'Pending', 'changes outside Review invalidate approval');
const legacy = candidate('legacy', {approvalStatus:'Approved', approverId:'R1', approvalTimestamp:'2026-09-01', auditLog:[{action:'APPROVED',detail:'Status changed to Reviewed'}]});
W.normalize(legacy); W.normalize(legacy);
assert.equal(legacy.approvalStatus, 'Pending');
assert.equal(legacy.recordStatus, 'Follow-Up');
assert.equal(legacy.verificationHistory.length, 1);
assert.equal(legacy.verificationHistory[0].approverId, 'R1');
assert.equal(legacy.auditLog.length, 1);
const ambiguous = candidate('ambiguous', {approvalStatus:'Approved',approverId:'R1',auditLog:[{action:'APPROVED',detail:'Approved in Review'}]});
W.normalize(ambiguous);
assert.equal(ambiguous.approvalStatus, 'Pending', 'unversioned association requires confirmation');
assert.equal(ambiguous.verificationReason, 'Legacy approval requires confirmation');
const rejected = candidate('rejected', {approvalStatus:'Rejected'}); W.normalize(rejected);
assert.equal(rejected.approvalStatus, 'Rejected');
const other = candidate('other', {eventId:'other',recordStatus:'Closed'});
c.eventId = legacy.eventId = ambiguous.eventId = rejected.eventId = 'fair';
assert.equal(W.population({event:'fair',status:'Follow-Up',verification:'Rejected draft'}).length, 1);
assert.equal(W.pileCounts({event:'other'}).Closed, 1);
W.setDraft(other, {summary:'Unsaved other'});
assert.equal(W.hasUnsavedDrafts(), true);
assert.equal(W.draft(c).summary, c.summary, 'drafts remain candidate-keyed');
const coverage = W.requiredCoverage([c]);
assert.equal(coverage.present, 3); assert.equal(coverage.expected, 3);
const rows = W.handoff([c]);
assert.equal(rows[0].verification, 'Needs verification');
assert.equal(rows[0].nextStepNotes, 'Ask about availability');
console.log('PASS review workflow: independent decisions, exact versions, conservative migration, drafts, scope and handoff');
