const assert = require('node:assert/strict');
const {loadApp} = require('./harness');
const T = loadApp(['analytics.js','components.js','skill-icons.js','views.js','review-workspace.js']);
const V = T.views, W = T.reviewWorkflow;
const event = T.currentEventId();
T.state.candidates = ['Reviewed','Follow-Up','New','Interview Requested','Closed'].map((status,i) => {
  const c = T.normalizeCandidate(T.intake.buildCandidate({firstName:'Synthetic '+i,lastName:'Example',email:'sample'+i+'@example.invalid'},{state:T.state}));
  Object.assign(c,{id:'review-'+i,eventId:event,recordStatus:status,summary:'Recorded observation '+i,notes:'Discussed coursework'});
  return c;
});
const c = T.state.candidates[0];
T.state.candidates.push({...c,id:'other-event',eventId:'another-event'});
assert.deepEqual(Array.from(W.population({event,status:'reviewed-follow-up'}),x=>x.id),['review-0','review-1'], 'default finder status scope excludes New, Interview Requested and Closed');
assert.equal(W.population({event,status:'all'}).length,5);
assert.equal(V.reviewState.filters.event,event);
assert.equal(V.reviewState.evidence,'resume');
let html = V.renderReview();
assert(html.includes('review-simplified'), 'two-panel Review');
assert(html.includes('Find candidate') && html.includes('Reviewed and Follow-Up'));
assert(html.includes(V._buildCardHtml(c,false)), 'left panel reuses actual card');
assert(html.includes('role="tab" id="review-tab-contact"'));
assert(html.includes('Recruiter recap') && html.includes('Approve recap'));
assert(!html.includes('review-piles') && !html.includes('data-review-compare'), 'no permanent piles or premature comparison');
assert(!html.includes('data-review-action="csv"') && !html.includes('results-return'));
assert(html.includes('id="reviewSummary"') && html.includes('data-review-action="cancel-edit"'));
W.setDraft(c,{summary:'Candidate-specific unsaved correction'});
W.changeStatus(c,'Closed');
html = V.renderReview();
assert(html.includes('no longer matches') && html.includes('Candidate-specific unsaved correction'));
assert.equal(W.label(c),'Needs verification','status is not approval');
V.reviewState.selected = 'review-1';
V.renderReview();
V.reviewState.selected = c.id;
assert(V.renderReview().includes('Candidate-specific unsaved correction'));
W.cancelDraft(c);
assert.equal(W.draft(c).summary,c.summary);
assert(!W.dirty(c));
assert(T.CONFIG.workflow.some(x=>x.key==='review'));
assert(!T.CONFIG.workflow.some(x=>x.key==='analytics'));
console.log('PASS simplified Review scope, shared card, independent status, retained drafts and cancel');
