import type { Candidate, CandidateFunction, CandidateStatus, CandidatePriority } from "./types"

export const EVENT = {
  name: "JBH Talent Hub 2026",
  date: "March 15, 2026",
  location: "University of Arkansas",
  tagline: "Connecting Top Talent with J.B. Hunt",
}

export const RECRUITERS = [
  { id: "r1", name: "Sarah Chen" },
  { id: "r2", name: "Marcus Williams" },
  { id: "r3", name: "Priya Sharma" },
]

export const UNIVERSITIES = [
  "University of Arkansas",
  "Arkansas State University",
  "University of Central Arkansas",
  "Ouachita Baptist University",
  "Henderson State University",
  "University of Memphis",
  "Mississippi State University",
  "University of Mississippi",
  "Louisiana Tech University",
  "Tulane University",
  "Texas A&M University",
  "University of Texas at Austin",
]

export const MAJORS: Record<string, string[]> = {
  "Supply Chain": ["Supply Chain Management", "Logistics", "Operations Management", "Business Administration"],
  "Transportation": ["Transportation Management", "Fleet Management", "Logistics Engineering"],
  "Engineering": ["Mechanical Engineering", "Electrical Engineering", "Civil Engineering", "Industrial Engineering", "Computer Engineering"],
  "Data Science": ["Data Science", "Computer Science", "Statistics", "Machine Learning", "Artificial Intelligence"],
  "Finance": ["Finance", "Accounting", "Economics", "Financial Planning"],
  "Marketing": ["Marketing", "Digital Marketing", "Communications", "Public Relations"],
  "Human Resources": ["Human Resources", "Organizational Psychology", "Business Management"],
  "Operations": ["Operations Management", "Supply Chain", "Business Operations"],
  "Sales": ["Sales Management", "Business Administration", "Marketing"],
  "Information Technology": ["Computer Science", "Information Systems", "Software Engineering", "Cybersecurity"],
}

export const FUNCTIONS: CandidateFunction[] = [
  "Supply Chain",
  "Transportation",
  "Engineering",
  "Data Science",
  "Finance",
  "Marketing",
  "Human Resources",
  "Operations",
  "Sales",
  "Information Technology",
]

export const PRIORITIES: CandidatePriority[] = ["Low", "Medium", "High"]

export const STATUSES: CandidateStatus[] = ["New", "Reviewed", "Follow-Up", "Interview Requested", "Closed"]

export const STATUS_COLORS: Record<CandidateStatus, string> = {
  New: "bg-muted text-muted-foreground",
  Reviewed: "bg-emerald-500 text-white",
  "Follow-Up": "bg-amber-500 text-white",
  "Interview Requested": "bg-primary text-primary-foreground",
  Closed: "bg-muted-foreground text-white",
}

export const QUICK_TAGS = [
  "Strong Communication",
  "Technical Skills",
  "Leadership Potential",
  "Cultural Fit",
  "Quick Learner",
  "Team Player",
  "Problem Solver",
  "Initiative Taker",
  "Detail Oriented",
  "Adaptable",
  "Analytics Minded",
  "Client Focused",
]

export const OVERVIEW_STATS = [
  { label: "Total Scanned", value: "0", icon: "users", color: "text-primary" },
  { label: "Interview Requests", value: "0", icon: "calendar", color: "text-emerald-600" },
  { label: "Avg Review Time", value: "2.4m", icon: "clock", color: "text-amber-600" },
  { label: "Data Completeness", value: "87%", icon: "chart", color: "text-primary" },
]

export const seedCandidates: Candidate[] = [
  {
    id: "TQ-0001",
    firstName: "Marcus",
    lastName: "Johnson",
    email: "marcus.j@uark.edu",
    phone: "501-555-0101",
    university: "University of Arkansas",
    major: "Supply Chain Management",
    function: "Supply Chain",
    graduationDate: "2026-05",
    gpa: "3.8",
    workAuthorization: "US Citizen",
    resumeFileName: "marcus_johnson_resume.pdf",
    notes: "Impressive understanding of logistics optimization. Mentioned experience with route planning algorithms.",
    status: "Reviewed",
    priority: "High",
    quickTags: ["Strong Communication", "Technical Skills", "Leadership Potential"],
    aiSnapshot: "Marcus is a senior Supply Chain Management student at the University of Arkansas with a 3.8 GPA. He brings hands-on experience from a summer internship at a regional distribution center where he optimized warehouse layout, reducing picking time by 15%. His coursework in operations research and data analytics provides a strong analytical foundation. He demonstrated excellent communication skills during the career fair and showed genuine interest in J.B. Hunt's intermodal services division.",
    aiSkills: ["Data Analysis", "Warehouse Optimization", "ERP Systems", "Route Planning", "Process Improvement"],
    aiScore: 92,
    recordings: [],
    createdAt: "2026-03-15T09:30:00Z",
    updatedAt: "2026-03-15T09:45:00Z",
    auditLog: [
      { timestamp: "2026-03-15T09:30:00Z", action: "created", detail: "Candidate added via intake form" },
      { timestamp: "2026-03-15T09:45:00Z", action: "status_change", detail: "New -> Reviewed" },
    ],
  },
  {
    id: "TQ-0002",
    firstName: "Priya",
    lastName: "Patel",
    email: "priya.p@astate.edu",
    phone: "870-555-0202",
    university: "Arkansas State University",
    major: "Computer Science",
    function: "Data Science",
    graduationDate: "2026-12",
    gpa: "3.9",
    workAuthorization: "US Citizen",
    resumeFileName: "priya_patel_resume.pdf",
    notes: "Outstanding technical interview. Built a real-time freight tracking dashboard as a class project.",
    status: "Interview Requested",
    priority: "High",
    quickTags: ["Technical Skills", "Analytics Minded", "Problem Solver"],
    aiSnapshot: "Priya is a graduate student in Computer Science at Arkansas State University with a near-perfect 3.9 GPA. Her capstone project involved building a real-time freight tracking dashboard using React and WebSockets, directly relevant to J.B. Hunt's technology needs. She has completed three internships including a data engineering role at a Fortune 500 logistics company. Her GitHub showcases multiple open-source contributions to supply chain analytics tools. She expressed strong interest in the Data Science team.",
    aiSkills: ["Machine Learning", "Python", "React", "WebSockets", "Data Visualization", "SQL"],
    aiScore: 96,
    recordings: [],
    createdAt: "2026-03-15T10:00:00Z",
    updatedAt: "2026-03-15T10:30:00Z",
    auditLog: [
      { timestamp: "2026-03-15T10:00:00Z", action: "created", detail: "Candidate added via intake form" },
      { timestamp: "2026-03-15T10:30:00Z", action: "status_change", detail: "New -> Interview Requested" },
    ],
  },
  {
    id: "TQ-0003",
    firstName: "Jordan",
    lastName: "Williams",
    email: "jordan.w@uca.edu",
    phone: "501-555-0303",
    university: "University of Central Arkansas",
    major: "Business Administration",
    function: "Operations",
    graduationDate: "2026-05",
    gpa: "3.5",
    workAuthorization: "US Citizen",
    resumeFileName: "jordan_williams_resume.pdf",
    notes: "Good energy, strong interest in operations management track.",
    status: "New",
    priority: "Medium",
    quickTags: ["Team Player", "Initiative Taker"],
    aiSnapshot: "Jordan is a senior Business Administration major at UCA with a solid 3.5 GPA. He has two years of part-time experience in retail operations management, where he supervised teams of 8-12 associates. His coursework in operations management and organizational behavior provides a good foundation. He is particularly interested in J.B. Hunt's fleet management operations and expressed willingness to relocate.",
    aiSkills: ["Team Leadership", "Inventory Management", "Customer Service", "Scheduling"],
    aiScore: 78,
    recordings: [],
    createdAt: "2026-03-15T11:00:00Z",
    updatedAt: "2026-03-15T11:00:00Z",
    auditLog: [
      { timestamp: "2026-03-15T11:00:00Z", action: "created", detail: "Candidate added via intake form" },
    ],
  },
  {
    id: "TQ-0004",
    firstName: "Aisha",
    lastName: "Thompson",
    email: "aisha.t@memphis.edu",
    phone: "901-555-0404",
    university: "University of Memphis",
    major: "Finance",
    function: "Finance",
    graduationDate: "2026-05",
    gpa: "3.7",
    workAuthorization: "US Citizen",
    resumeFileName: "aisha_thompson_resume.pdf",
    notes: "Finance focus, interested in transportation economics.",
    status: "Follow-Up",
    priority: "Medium",
    quickTags: ["Analytics Minded", "Detail Oriented"],
    aiSnapshot: "Aisha is a Finance major at the University of Memphis with a 3.7 GPA. She completed a summer analyst role at a regional bank where she developed financial models for commercial lending. Her interest in transportation economics aligns well with J.B. Hunt's financial planning needs. She demonstrated strong analytical skills during our conversation and asked thoughtful questions about the company's intermodal investment strategy.",
    aiSkills: ["Financial Modeling", "Excel", "Data Analysis", "Risk Assessment", "Commercial Lending"],
    aiScore: 85,
    recordings: [],
    createdAt: "2026-03-15T11:30:00Z",
    updatedAt: "2026-03-15T12:00:00Z",
    auditLog: [
      { timestamp: "2026-03-15T11:30:00Z", action: "created", detail: "Candidate added via intake form" },
      { timestamp: "2026-03-15T12:00:00Z", action: "status_change", detail: "New -> Follow-Up" },
    ],
  },
  {
    id: "TQ-0005",
    firstName: "Carlos",
    lastName: "Ramirez",
    email: "carlos.r@msstate.edu",
    phone: "662-555-0505",
    university: "Mississippi State University",
    major: "Industrial Engineering",
    function: "Engineering",
    graduationDate: "2026-12",
    gpa: "3.6",
    workAuthorization: "Permanent Resident",
    resumeFileName: "carlos_ramirez_resume.pdf",
    notes: "Strong engineering background, interested in process optimization.",
    status: "Reviewed",
    priority: "Medium",
    quickTags: ["Problem Solver", "Technical Skills"],
    aiSnapshot: "Carlos is an Industrial Engineering student at Mississippi State with a 3.6 GPA. He has completed co-op rotations at two manufacturing facilities where he applied lean Six Sigma principles. His senior design project focused on optimizing last-mile delivery routes, reducing estimated delivery times by 12%. He is authorized to work in the US as a permanent resident and is interested in J.B. Hunt's engineering and operations improvement initiatives.",
    aiSkills: ["Lean Six Sigma", "Process Optimization", "MATLAB", "AutoCAD", "Statistical Analysis"],
    aiScore: 83,
    recordings: [],
    createdAt: "2026-03-15T12:30:00Z",
    updatedAt: "2026-03-15T12:45:00Z",
    auditLog: [
      { timestamp: "2026-03-15T12:30:00Z", action: "created", detail: "Candidate added via intake form" },
      { timestamp: "2026-03-15T12:45:00Z", action: "status_change", detail: "New -> Reviewed" },
    ],
  },
  {
    id: "TQ-0006",
    firstName: "Emily",
    lastName: "Chen",
    email: "emily.c@utexas.edu",
    phone: "512-555-0606",
    university: "University of Texas at Austin",
    major: "Marketing",
    function: "Marketing",
    graduationDate: "2026-05",
    gpa: "3.9",
    workAuthorization: "US Citizen",
    resumeFileName: "emily_chen_resume.pdf",
    notes: "Exceptional marketing portfolio. Strong digital presence and social media strategy skills.",
    status: "New",
    priority: "High",
    quickTags: ["Strong Communication", "Creative", "Initiative Taker"],
    aiSnapshot: "Emily is a Marketing major at UT Austin with a 3.9 GPA and an impressive portfolio. She managed social media for a startup that grew its following by 300% in 6 months. Her capstone project analyzed brand perception in the logistics industry, specifically examining how trucking companies can improve recruitment messaging. She brings expertise in content creation, analytics, and digital advertising that would directly benefit J.B. Hunt's marketing initiatives.",
    aiSkills: ["Digital Marketing", "Social Media Strategy", "Content Creation", "Google Analytics", "Adobe Creative Suite"],
    aiScore: 91,
    recordings: [],
    createdAt: "2026-03-15T13:00:00Z",
    updatedAt: "2026-03-15T13:00:00Z",
    auditLog: [
      { timestamp: "2026-03-15T13:00:00Z", action: "created", detail: "Candidate added via intake form" },
    ],
  },
]
